name: create_templates
description: Генератор шаблонов для проектов на Dart
version: 1.0.2
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

executables:
  create_templates: bin/create_templates.dart

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  path: ^1.9.1
  yaml: ^3.1.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
